import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Maps from '@/client/components/Maps';
import { Provider } from 'react-redux';
import store from '@/client/utils/store';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        <Provider store={store}>
          <Maps />
        </Provider>
      </main>
    </>
  );
}
